# Generated by Django 6.0.4 on 2026-07-06 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_series_collection_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('provider_name', models.CharField(max_length=100)),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('display_priority', models.IntegerField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='app.series')),
            ],
            options={
                'ordering': ['display_priority'],
                'unique_together': {('series', 'provider_id')},
            },
        ),
    ]
