# Generated by Django 6.0.4 on 2026-07-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_streaming_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tmdb_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
