# Generated by Django 6.0.4 on 2026-07-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_series_tmdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='tmdb_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
